### ISSUE TITLE
HCL2 to Vault Value Result

### ISSUE THREAD

**Issue by evanfreed** [elastic/harp#58]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/efreed/Library/Caches/go-build"
GOENV="/Users/efreed/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/efreed/.gvm/pkgsets/go1.16/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/efreed/.gvm/pkgsets/go1.16/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/efreed/.gvm/gos/go1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/efreed/.gvm/gos/go1.16/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hb/cqz2kv_j6gv66cbzp0pr1zdh0000gn/T/go-build4035214422=/tmp/go-build -gno-record-gcc-switches -fno-common"
GOROOT/bin/go version: go version go1.16 darwin/amd64
GOROOT/bin/go tool compile -V: compile version go1.16
uname -v: Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
lldb --version: lldb-1205.0.28.2
Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
</pre></details>

### What version of Secret are you using (`harp version`)?

<pre>
$ harp version
cmd/harp/v0.1.17-7-g89a4f9e [main:89a4f9e] (Go: go1.16.6, Flags: defaults, User: golang, Date: 2021-07-13T10:22:48Z)
</pre>

#### spec.yml

```yml
apiVersion: harp.elastic.co/v1
kind: BundleTemplate
meta:
  name: "test-application-credentials"
  description: "Credentials for a test application"
  owner: no-reply@elastic.co
spec:
  selector:
    quality: "{{ .Values.quality }}"
    platform: "ess"
    product: "test-application"
    version: "1.0.0"
  namespaces:
    platform:
      - region: "global"
        components:
          - name: "test-application"
            secrets:
              - suffix: "credentials"
                description: "testing credentials"
                template: |-
                  {
                    "cluster_username": "{{ .Values.variable.cluster_username }}"
                  }
```

#### main.tf

```hcl
variable "cluster_username" {
  type    = string
  default = "myuser"
}
```

```shell
harp from bundle-template --in spec.yml  --out - --values main.tf:hcl2 --set quality=qa | harp bundle dump --in - --data-only | jq .
{
  "platform/qa/ess/global/test-application/credentials": {
    "cluster_username": "map[default:myuser type:${string}]"
  }
}
```

```shell
harp from bundle-template --in spec.yml  --out - --values main.tf:hcl2 --set quality=qa | harp to vault --in - --with-metadata
```

### What did you expect to see?

I expected to see a key: `cluster_username` and value: `myuser`.

When trying to read vault from another terraform workspace `data.vault_generic_secret...`, its unable to handle `map[default:myuser type:${string}]`.

### What did you see instead?

<img width="492" alt="Screen Shot 2021-07-21 at 10 39 01 AM" src="https://user-images.githubusercontent.com/2314084/126518295-6803823e-1527-4afe-aaa8-ced4f49afe4a.png">
